[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# Include package data files if any are specified (e.g., via MANIFEST.in or package_data)
include-package-data = true

# Use the src directory as the package root
[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = [
    "tests*",
    "docs*",
    "examples*",
]

[project]
name = "parakeet"
version = "0.1.0"
description = "A Python wrapper around the Robinhood API"
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
authors = [
    { name = "Ryan Miller", email = "mrzodge@gmail.com" },
]
keywords = ["robinhood", "parakeet", "finance app", "stocks", "options", "trading", "investing"]
requires-python = ">=3.9"
dependencies = [
    "requests",
    "pyotp",
    "python-dotenv",
    "cryptography",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/RvanMiller/parakeet"
Repository = "https://github.com/RvanMiller/parakeet"

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]
