name: Deploy Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Non-Prod Environment

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --statistics
    - name: Test robinhood with pytest
      env:
        rh_username: ${{ secrets.rh_username }}
        rh_password: ${{ secrets.rh_password }}
        rh_mfa_code: ${{ secrets.rh_mfa_code }}
      run: |
        pip install -e ".[test]"
        pytest tests/test_robinhood.py
