name: Deploy Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Non-Prod Environment

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with ruff
      run: |
        poetry run ruff check .
    - name: Test robinhood with pytest
      env:
        rh_username: ${{ secrets.rh_username }}
        rh_password: ${{ secrets.rh_password }}
        rh_mfa_code: ${{ secrets.rh_mfa_code }}
      run: |
        poetry run pytest tests/legacy/unit_tests.py
